name: stack-internal-lib-bug
version: '0.1.0.0'
category: Web
author: David Kraeutmann
maintainer: kane@kane.cx
copyright: 2018 David Kraeutmann
license: BSD3

dependencies:
- base

library:
  source-dirs: src

internal-libraries:
  a:
    source-dirs: src-a

